spring:
  application:
    name: commerce-payment

  datasource:
    url: jdbc:mysql://localhost:3306/payment_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: payment_user
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true