spring:
  application:
    name: commerce-payment

  datasource:
    url: jdbc:mysql://localhost:3306/payment_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: payment_user
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true


# JWT 설정
jwt:
  secret: "c3BhcnRhLXBheW1lbnQtand0LXNlY3JldC1rZXktZm9yLWJvb3RjYW1wLTIwMjYtdmVyeS1sb25nLXNlY3JldA=="  # Base64 encoded
  expiration: 3600000  # 1시간 (ms)